apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qhx2fjurh-python
  janus-idp.io/tekton: qhx2fjurh-python
  backstage.io/kubernetes-id: qhx2fjurh-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qhx2fjurh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
